# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pong.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pong.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npong.proto\x12\x04pong\"\x1f\n\x0f\x43onectarRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"I\n\x10\x43onectarResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x12\n\nid_jogador\x18\x02 \x01(\x05\x12\x10\n\x08mensagem\x18\x03 \x01(\t\"3\n\x0cMoverRequest\x12\x12\n\nid_jogador\x18\x01 \x01(\x05\x12\x0f\n\x07\x64irecao\x18\x02 \x01(\t\" \n\rMoverResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\"#\n\rEstadoRequest\x12\x12\n\nid_jogador\x18\x01 \x01(\x05\"\xb9\x01\n\x0e\x45stadoResponse\x12\x0e\n\x06\x62ola_x\x18\x01 \x01(\x02\x12\x0e\n\x06\x62ola_y\x18\x02 \x01(\x02\x12\x12\n\nraquete1_y\x18\x03 \x01(\x02\x12\x12\n\nraquete2_y\x18\x04 \x01(\x02\x12\x0f\n\x07placar1\x18\x05 \x01(\x05\x12\x0f\n\x07placar2\x18\x06 \x01(\x05\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x10\n\x08vencedor\x18\x08 \x01(\x05\x12\x0e\n\x06motivo\x18\t \x01(\t\x12\x0b\n\x03seq\x18\n \x01(\x03\x32\xc2\x01\n\x0bPongService\x12@\n\x0f\x43onectarJogador\x12\x15.pong.ConectarRequest\x1a\x16.pong.ConectarResponse\x12\x37\n\x0cMoverRaquete\x12\x12.pong.MoverRequest\x1a\x13.pong.MoverResponse\x12\x38\n\x0bObterEstado\x12\x13.pong.EstadoRequest\x1a\x14.pong.EstadoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pong_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONECTARREQUEST']._serialized_start=20
  _globals['_CONECTARREQUEST']._serialized_end=51
  _globals['_CONECTARRESPONSE']._serialized_start=53
  _globals['_CONECTARRESPONSE']._serialized_end=126
  _globals['_MOVERREQUEST']._serialized_start=128
  _globals['_MOVERREQUEST']._serialized_end=179
  _globals['_MOVERRESPONSE']._serialized_start=181
  _globals['_MOVERRESPONSE']._serialized_end=213
  _globals['_ESTADOREQUEST']._serialized_start=215
  _globals['_ESTADOREQUEST']._serialized_end=250
  _globals['_ESTADORESPONSE']._serialized_start=253
  _globals['_ESTADORESPONSE']._serialized_end=438
  _globals['_PONGSERVICE']._serialized_start=441
  _globals['_PONGSERVICE']._serialized_end=635
# @@protoc_insertion_point(module_scope)
