# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pong_pb2 as pong__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pong_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PongServiceStub(object):
    """=====================================================================
    SERVIÇO PONG — Interface Remota Principal
    =====================================================================
    Expõe os 3 métodos RPC que os clientes invocam remotamente.
    Equivalente ao conceito de Java RMI em Python via gRPC.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConectarJogador = channel.unary_unary(
                '/pong.PongService/ConectarJogador',
                request_serializer=pong__pb2.ConectarRequest.SerializeToString,
                response_deserializer=pong__pb2.ConectarResponse.FromString,
                _registered_method=True)
        self.MoverRaquete = channel.unary_unary(
                '/pong.PongService/MoverRaquete',
                request_serializer=pong__pb2.MoverRequest.SerializeToString,
                response_deserializer=pong__pb2.MoverResponse.FromString,
                _registered_method=True)
        self.ObterEstado = channel.unary_unary(
                '/pong.PongService/ObterEstado',
                request_serializer=pong__pb2.EstadoRequest.SerializeToString,
                response_deserializer=pong__pb2.EstadoResponse.FromString,
                _registered_method=True)


class PongServiceServicer(object):
    """=====================================================================
    SERVIÇO PONG — Interface Remota Principal
    =====================================================================
    Expõe os 3 métodos RPC que os clientes invocam remotamente.
    Equivalente ao conceito de Java RMI em Python via gRPC.

    """

    def ConectarJogador(self, request, context):
        """Registra um novo jogador. Retorna ID 1 ou 2.
        Bloqueia o segundo cliente até que o primeiro já esteja conectado.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoverRaquete(self, request, context):
        """Move a raquete do jogador informado para cima ou para baixo.
        Chamado a cada frame em que o jogador pressiona uma tecla.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterEstado(self, request, context):
        """Retorna o estado completo e atual do jogo.
        Chamado em polling pelo cliente a cada ~16ms (60fps).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PongServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConectarJogador': grpc.unary_unary_rpc_method_handler(
                    servicer.ConectarJogador,
                    request_deserializer=pong__pb2.ConectarRequest.FromString,
                    response_serializer=pong__pb2.ConectarResponse.SerializeToString,
            ),
            'MoverRaquete': grpc.unary_unary_rpc_method_handler(
                    servicer.MoverRaquete,
                    request_deserializer=pong__pb2.MoverRequest.FromString,
                    response_serializer=pong__pb2.MoverResponse.SerializeToString,
            ),
            'ObterEstado': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterEstado,
                    request_deserializer=pong__pb2.EstadoRequest.FromString,
                    response_serializer=pong__pb2.EstadoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pong.PongService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pong.PongService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PongService(object):
    """=====================================================================
    SERVIÇO PONG — Interface Remota Principal
    =====================================================================
    Expõe os 3 métodos RPC que os clientes invocam remotamente.
    Equivalente ao conceito de Java RMI em Python via gRPC.

    """

    @staticmethod
    def ConectarJogador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pong.PongService/ConectarJogador',
            pong__pb2.ConectarRequest.SerializeToString,
            pong__pb2.ConectarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoverRaquete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pong.PongService/MoverRaquete',
            pong__pb2.MoverRequest.SerializeToString,
            pong__pb2.MoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterEstado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pong.PongService/ObterEstado',
            pong__pb2.EstadoRequest.SerializeToString,
            pong__pb2.EstadoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
